// Backtest artifact schema + validation.
//
// The Accuracy page previously rendered a legacy artifact produced by a harness
// that scored a *substitute* model (it injected a different fixture multiplier
// and clean-sheet formula, and filtered the evaluation set on post-match
// minutes). Those numbers were published as if they described the shipped
// model. This module makes the schema explicit and refuses anything it does not
// recognise, so that cannot silently recur.

/**
 * Schema versions this build can render.
 *
 * 8 is the current one: it adds `minutes_model`, the first measurement of
 * `p_start` — the component that gates every other number on this page. Purely
 * additive, so a v7 artifact renders exactly as it did, minus that one section.
 *
 * 7 is kept alongside it deliberately, and this is a transition state rather
 * than a permanent pair. `backtest.json` is generated by hand (`python -m
 * gaffer.backtest --write`) and appears in no workflow, so between a deploy
 * carrying this code and someone regenerating the artifact the published file
 * is still v7; accepting only 8 would blank the Accuracy page for that window.
 * Drop 7 once the deployed artifact is v8.
 *
 * 6 was dropped when 8 arrived: keeping a three-wide window means the page can
 * render a measurement two splits old with nothing on it saying so.
 *
 * Supported rather than rejected because v7 is not *wrong*. Versions 3, 4 and 5
 * are refused below because rendering them would put a withdrawn or mislabelled
 * number back on the page. A v7 artifact is an honest measurement that is
 * missing a section — superseded, not retracted — and that distinction is the
 * entire reason the two lists exist separately.
 */
export const SUPPORTED_SCHEMA_VERSIONS = [7, 8] as const
/**
 * Versions we know about and deliberately refuse.
 *
 * 3 is refused: it reported `fpl_xp` and `ensemble` as measured baselines, and
 * those were computed from the archive's `xP` column, which is inadmissible.
 * Rendering a v3 artifact would put a withdrawn number back on the page.
 *
 * 4 is refused: it reported one collapsed model verdict, which said trained
 * models lost every decision metric. Ridge did not. A v4 artifact cannot show
 * the per-candidate evidence, so it would repeat the claim it got wrong.
 *
 * 5 is refused: it evaluated GW2 onwards while describing itself as covering
 * GW1, so its headline numbers are in-season numbers wearing an all-season
 * label — and it carries no `pre_season` block, so a build rendering it would
 * present the pre-season regime as measured when it never was.
 *
 * 6 is refused as of schema 8, and for a different reason from the four above
 * it: it is honest, but it reports 2024-25 under a page that now describes the
 * 2025-26 split, and it predates every minutes number. Two splits of drift is
 * further than a transition window should stretch.
 */
export const REJECTED_SCHEMA_VERSIONS = [1, 2, 3, 4, 5, 6] as const

export interface CalBin {
  pred: number
  actual: number
  haul_rate: number
  n: number
}

export interface HorizonDecisions {
  gameweeks_scored: number
  xi_points_per_gw: number
  xi_regret_per_gw: number | null
  captain_points_per_gw: number
  captain_regret_per_gw: number
  captain_accuracy_pct: number
}

export interface HorizonBlock {
  n: number
  mae: Record<string, number>
  rank_corr: Record<string, number>
  decisions?: Record<string, HorizonDecisions | Record<string, never>>
  transfers?: Record<string, { with_transfers: number; hold_squad: number; gain: number; gameweeks: number }>
}

/**
 * GW1 measured on its own.
 *
 * A separate block rather than a row in `per_horizon` because it is a separate
 * regime: no season-to-date history exists, so the model runs on prior-season
 * rates and the price prior alone, and the naive baseline — cumulative
 * season-to-date points-per-game — does not exist at all. `naive_baseline`
 * carries that explanation rather than a number, so the page cannot imply a
 * comparison that was never made.
 */
export interface PreSeasonBlock {
  decision_gw: number
  n: number
  regime: string
  mae: Record<string, number>
  rank_corr: Record<string, number>
  decisions?: Record<string, HorizonDecisions | Record<string, never>>
  /** Why the `decisions` numbers above are one evening, not a rate. */
  decisions_caveat?: string
  zero_minute_share_pct?: number
  naive_baseline: string
}

/** One decile of the start-probability calibration curve. */
export interface StartCalBin {
  pred: number
  actual: number
  appear_rate: number
  n: number
}

/** One of the three shipped minutes badges, scored. */
export interface StartBand {
  band: string
  n: number
  /** Mean `p_start` of the players wearing this badge — what it claimed. */
  claimed: number
  /** How often they then started — what it was worth. */
  start_rate: number
  appear_rate: number
  exp_minutes: number
  actual_minutes: number
}

/** Which arm of the shipped minutes gate produced a prediction, and its skill. */
export interface MinutesBranch {
  branch: string
  n: number
  share_pct: number
  mean_p_start: number
  start_rate: number
  brier: number
  /** Negative means worse than quoting this group's own base rate. */
  brier_skill: number
}

export interface MinutesHorizon {
  n: number
  start_rate: number
  brier: Record<string, number>
  brier_skill: Record<string, number>
  auc: Record<string, number>
  exp_minutes_mae: Record<string, number>
  paired_vs_baseline?: Record<string, {
    gameweeks: number
    diff: number | null
    ci95?: [number, number]
    gameweeks_model_better?: number
    gameweeks_model_worse?: number
    note?: string
  }>
}

/**
 * A11 — the minutes model, measured.
 *
 * `measured: false` is a real state and must render as one: a season with no
 * `starts` column has no start outcome to score against, and saying so is the
 * honest answer rather than quietly dropping the section.
 */
export interface MinutesModel {
  measured: boolean
  reason?: string
  season?: string
  model_version?: string
  target?: string
  unit?: string
  why_these_metrics?: string
  decision_gameweeks?: string
  coverage?: Record<string, number | string>
  leakage_check?: { enforced: boolean; post_match_fields_in_features: string[]; policy: string }
  baselines?: Record<string, string>
  per_horizon?: Record<string, MinutesHorizon>
  calibration?: {
    overall: StartCalBin[]
    considered?: StartCalBin[]
    considered_rank_cut?: number
    note?: string
  }
  bands?: {
    overall: StartBand[]
    considered?: StartBand[]
    considered_400?: StartBand[]
    pre_season?: StartBand[]
    pre_season_considered?: StartBand[]
    note?: string
  }
  branches?: MinutesBranch[]
  branch_note?: string
  pre_season?: Record<string, number | string>
  candidate_fix?: Record<string, unknown>
  limitations?: string[]
  verdict?: string
  live_audit?: Record<string, unknown>
}

/** A baseline that was published and then retracted, with its old numbers. */
export interface WithdrawnBaseline {
  withdrawn_in_schema: number
  previously_reported: Record<string, number>
  reason: string
}

export interface BacktestV6 {
  schema_version: number
  model_version: string
  dataset: string
  season: string
  decision_gameweeks: string
  horizons: number[]
  coverage: {
    rows_evaluated: number
    zero_minute_rows_retained: number
    zero_minute_share_pct: number
    decision_gws?: number
    excluded?: Record<string, unknown>
  }
  leakage_check: {
    enforced: boolean
    post_match_fields_in_features: string[]
    policy: string
  }
  per_horizon: Record<string, HorizonBlock>
  /** Absent on an artifact whose season had no evaluable GW1. */
  pre_season?: PreSeasonBlock | Record<string, never>
  calibration: {
    overall: CalBin[]
    /** G20 — restricted to player-gameweeks where the player featured. */
    appeared?: CalBin[]
    by_position?: Record<string, CalBin[]>
    note?: string
  }
  limitations: string[]
  generated_at: string
  baselines?: Record<string, Record<string, number | string>>
  ablations?: Array<Record<string, unknown>>
  shipped_projection?: Record<string, string>
  withdrawn_baselines?: Record<string, WithdrawnBaseline | string>
  model_candidates?: ModelCandidates
  /** Absent on a v7 artifact, which predates the measurement entirely. */
  minutes_model?: MinutesModel
}

/** One horizon's paired result for a candidate. */
export interface CandidateHorizon {
  candidate_xi: number
  diff: number
  ci95: [number, number]
  p_better?: number
  wins?: number
  losses?: number
}

export interface ModelCandidate {
  candidate: string
  label?: string
  detail?: string
  decision: 'rejected' | 'inconclusive' | 'invalid_experiment' | 'shipped'
  reason: string
  worse_at_every_horizon?: boolean | null
  per_horizon?: Record<string, CandidateHorizon>
  statistical?: Record<string, Record<string, number>>
  captain_accuracy_pct_h1?: number
  captain_regret_per_gw_h1?: number
  limitations?: string[]
}

export interface ModelCandidates {
  evaluation_version?: string
  outcome?: string
  /** U38 — present in every artifact and previously undeclared, so a consumer
   *  reading them got `any` and no help from the compiler. */
  status?: string
  measured_on_season?: string
  protocol?: string
  heuristic_reference?: {
    xi_points_per_gw?: Record<string, number>
    captain_accuracy_pct_h1?: number
    captain_regret_per_gw_h1?: number
  }
  /** What the shipped model scores on the season the candidates were NOT run
   *  on. Deliberately unpaired — see the artifact's own `note`. */
  current_split_reference?: {
    measured_on_season?: string
    measured_at_model_version?: string
    note?: string
    xi_points_per_gw?: Record<string, number>
    captain_points_per_gw_h1?: number
    captain_accuracy_pct_h1?: number
    captain_regret_per_gw_h1?: number
    rank_corr?: Record<string, number>
    mae?: Record<string, number>
    rank_corr_and_mae?: string
  }
  candidates: ModelCandidate[]
  not_ruled_out?: string
  /** What running the rejected candidate actually cost. */
  cost?: {
    fit_seconds?: number
    predict_seconds?: number
    train_rows?: number
    predict_rows?: number
    [k: string]: unknown
  }
  /** Paths deleted when the ML line was closed, kept so the decision is
   *  auditable rather than merely asserted. */
  removed?: string[]
}

export type BacktestState =
  | { kind: 'ok'; data: BacktestV6 }
  | { kind: 'missing' }
  | { kind: 'unsupported'; version: unknown; detail: string }
  | { kind: 'malformed'; detail: string }

const REQUIRED_KEYS = [
  'model_version', 'season', 'per_horizon', 'coverage',
  'leakage_check', 'limitations', 'generated_at',
] as const

/**
 * Validate a raw backtest artifact.
 *
 * Deliberately strict: an unrecognised or malformed artifact renders an
 * explanatory error, never a number. Publishing a stale accuracy claim is worse
 * than publishing none.
 */
export function parseBacktest(raw: unknown): BacktestState {
  if (raw == null) return { kind: 'missing' }
  if (typeof raw !== 'object' || Array.isArray(raw)) {
    return { kind: 'malformed', detail: `expected an object, got ${Array.isArray(raw) ? 'an array' : typeof raw}` }
  }

  const obj = raw as Record<string, unknown>
  const version = obj.schema_version

  if (version === undefined) {
    // The legacy artifact had no schema_version at all.
    return {
      kind: 'unsupported',
      version: undefined,
      detail:
        'This artifact predates the corrected backtest. It was produced by a harness ' +
        'that scored a substitute model and filtered the evaluation set on post-match ' +
        'minutes, so its numbers do not describe the shipped model.',
    }
  }
  // Widened rather than cast to the current literal, matching `parseLive`. The
  // old `version as 5` had to be edited on every schema bump and failed the type
  // check when it was not — a compile error each time, but only by luck.
  if (typeof version !== 'number'
      || !(SUPPORTED_SCHEMA_VERSIONS as readonly number[]).includes(version)) {
    return {
      kind: 'unsupported',
      version,
      detail: `schema_version ${JSON.stringify(version)} is not renderable by this build ` +
        `(supported: ${SUPPORTED_SCHEMA_VERSIONS.join(', ')}).`,
    }
  }

  for (const k of REQUIRED_KEYS) {
    if (!(k in obj)) return { kind: 'malformed', detail: `missing required field '${k}'` }
  }
  if (typeof obj.per_horizon !== 'object' || obj.per_horizon == null) {
    return { kind: 'malformed', detail: "'per_horizon' must be an object" }
  }
  if (Object.keys(obj.per_horizon as object).length === 0) {
    return { kind: 'malformed', detail: "'per_horizon' is empty — nothing was evaluated" }
  }
  if (!Array.isArray(obj.limitations)) {
    return { kind: 'malformed', detail: "'limitations' must be an array" }
  }
  const leak = obj.leakage_check as Record<string, unknown> | undefined
  if (!leak || typeof leak.enforced !== 'boolean') {
    return { kind: 'malformed', detail: "'leakage_check.enforced' must be a boolean" }
  }

  return { kind: 'ok', data: obj as unknown as BacktestV6 }
}

/** Horizons present, in numeric order. */
export function horizonKeys(bt: BacktestV6): string[] {
  return Object.keys(bt.per_horizon).sort((a, b) => Number(a) - Number(b))
}

/** Every method named anywhere in the per-horizon blocks. */
export function methodsIn(bt: BacktestV6): string[] {
  const seen = new Set<string>()
  for (const k of horizonKeys(bt)) {
    for (const m of Object.keys(bt.per_horizon[k].rank_corr ?? {})) seen.add(m)
  }
  return [...seen]
}

/** True when the leakage guard ran and found nothing. */
export function leakageClean(bt: BacktestV6): boolean {
  return bt.leakage_check.enforced &&
    (bt.leakage_check.post_match_fields_in_features?.length ?? 0) === 0
}

export const METHOD_LABELS: Record<string, string> = {
  gaffer: 'Gaffer (component model)',
  naive: 'Recent-form average',
  // Retained so a withdrawn baseline still has a name if it ever appears in a
  // `withdrawn_baselines` block. It must never appear in `per_horizon`.
  fpl_xp: "FPL's own xP",
  ensemble: 'Gaffer + FPL xP blend',
}

/** Baselines that were retracted, newest schema first. Empty when there are none. */
export function withdrawn(bt: BacktestV6): Array<{ key: string; label: string; entry: WithdrawnBaseline }> {
  const out: Array<{ key: string; label: string; entry: WithdrawnBaseline }> = []
  for (const [key, entry] of Object.entries(bt.withdrawn_baselines ?? {})) {
    if (entry && typeof entry === 'object' && 'reason' in entry) {
      out.push({ key, label: METHOD_LABELS[key] ?? key, entry: entry as WithdrawnBaseline })
    }
  }
  return out
}

/**
 * Every evaluated candidate, in artifact order.
 *
 * The page must render all of them. Showing only the rejected one is how the
 * summary came to say "trained models lose every decision metric" when ridge
 * beat the heuristic at h=1.
 */
export function modelCandidates(bt: BacktestV6): ModelCandidate[] {
  const c = bt.model_candidates?.candidates
  return Array.isArray(c) ? c.filter((x) => x && typeof x.candidate === 'string') : []
}

/** Human label for a decision. `rejected` and `inconclusive` are not the same. */
export const DECISION_LABELS: Record<string, string> = {
  rejected: 'Rejected',
  inconclusive: 'Inconclusive — not selected',
  invalid_experiment: 'Invalid experiment',
  shipped: 'Shipped',
}

export const MINUTES_METHOD_LABELS: Record<string, string> = {
  gaffer: 'Gaffer p_start',
  start_rate_td: 'Starts / games so far',
  started_lag: 'Started last time',
  start_rate_r3: 'Started, last 3',
}

/**
 * The minutes block, only when it was actually measured.
 *
 * A `measured: false` block is deliberately NOT returned here — the page has a
 * separate branch for it. Folding the two together is how "we could not measure
 * this" becomes "there is nothing to show", which are different sentences.
 */
export function minutesModel(bt: BacktestV6): MinutesModel | null {
  const m = bt.minutes_model
  return m && m.measured === true ? m : null
}

/** The unmeasured case, with the reason it could not be measured. */
export function minutesUnmeasured(bt: BacktestV6): string | null {
  const m = bt.minutes_model
  return m && m.measured === false ? (m.reason ?? 'not measured') : null
}

/**
 * True when a baseline beats Gaffer's `p_start` at every horizon on Brier.
 *
 * Derived rather than written into the page, for the same reason
 * `baselineSweeps` is: a hand-typed verdict outlives the artifact that made it
 * true, and this one is a verdict against ourselves.
 */
export function minutesBaselineSweeps(m: MinutesModel): boolean {
  const hs = Object.keys(m.per_horizon ?? {})
  if (!hs.length) return false
  return hs.every((h) => {
    const b = m.per_horizon![h].brier
    const ours = b.gaffer
    return Object.entries(b).some(([k, v]) => k !== 'gaffer' && v < ours)
  })
}

/** Horizons in the minutes block, numerically ordered. */
export function minutesHorizonKeys(m: MinutesModel): string[] {
  return Object.keys(m.per_horizon ?? {}).sort((a, b) => Number(a) - Number(b))
}

/** Free-text consequence note on the withdrawal, when the artifact carries one. */
export function withdrawalConsequence(bt: BacktestV6): string | null {
  const c = bt.withdrawn_baselines?.consequence
  return typeof c === 'string' ? c : null
}


// ─────────────────────────────────────────────────────────────────────────────
// E1 — in-season calibration
//
// Everything above grades the model on an archive of finished seasons. This
// grades what Gaffer actually SHIPPED: the outcome distributions and per-player
// projections it froze before each deadline this season, scored against what
// happened. It arrives on `review.json` rather than `backtest.json` because that
// artifact is already validated by `gaffer.contract` and already loaded by the
// bundle; a new file would be published ahead of anything that checks it.
//
// The whole point of the block is the sample size, so the types below make `n`
// non-optional everywhere it exists, and the page must never render a figure
// without it.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Calibration-block schema versions this build can render.
 *
 * One entry today because there has only ever been one. When it bumps, ADD the
 * new version beside the old rather than replacing it — the artifact is written
 * by the pipeline and the page is deployed separately, so between a deploy and
 * the next refresh the published block is still the previous version, and a
 * single-version list blanks the section for that window. Same rule, and the
 * same reason, as `SUPPORTED_SCHEMA_VERSIONS` above.
 */
export const SUPPORTED_CALIBRATION_VERSIONS = [1] as const

export type PitDirection = 'runs_hot' | 'runs_cold' | 'no_detectable_bias'

/** Uniformity of a set of PIT values. `n` is not optional, by design. */
export interface PitStats {
  n: number
  mean: number | null
  mean_ci95: [number, number] | null
  median: number | null
  ks_d: number | null
  ks_critical_95: number | null
  rejects_uniform_at_95: boolean | null
  below_0_15: number
  above_0_85: number
  smallest_detectable_shift: number | null
  direction: PitDirection | null
  /** Present on the pooled population, which mixes reference classes. */
  caveat?: string
}

export interface PitGameweek {
  event: number
  percentile: number | null
  realised: number | null
  followed_advice: boolean | null
  distribution_size: number
  snapshot_as_of?: string | null
  snapshot_match?: string
  published_percentile?: number | null
  agrees_with_published?: boolean | null
  note?: string
}

export interface DistributionCalibration {
  status: string
  reportable: boolean
  reporting_floor_gameweeks: number
  gameweeks_short_of_the_floor: number
  verdict: string
  basis: string
  followed_the_advice: PitStats
  every_gameweek: PitStats
  gameweeks_followed: number
  gameweeks_diverged: number
  gameweeks_followed_unknown: number
  gameweeks_for_a_moderate_shift: number
  moderate_shift: number
  power_note: string
  interval_note?: string
  per_gameweek: PitGameweek[]
  recomputation?: {
    checked: number
    disagreed_with_the_published_percentile: number[]
    note: string
  }
}

export interface ProjectionErrorStats {
  n: number
  mae: number | null
  mean_predicted: number | null
  mean_actual: number | null
  bias: number | null
  bias_direction: 'over' | 'under' | 'none' | null
  baseline_mae: number | null
  skill_vs_pool_mean: number | null
}

export interface ProjectionCalibration {
  status: string
  reportable: boolean
  insufficient_reason?: string | null
  unavailable_reason?: string
  minimum_rows?: number
  minimum_gameweeks?: number
  unit?: string
  snapshot?: string
  gameweeks_measured?: number[]
  pooled?: ProjectionErrorStats
  per_gameweek?: Array<ProjectionErrorStats & { gameweek: number; as_of: string | null }>
  curve?: CalBin[]
  curve_summary?: {
    top_bin: CalBin
    top_bin_gap: number
    top_bin_direction: 'over' | 'under' | 'none'
    note: string
  } | null
  appeared?: ProjectionErrorStats & { curve?: CalBin[]; caveat: string }
  baselines?: {
    pool_mean: string
    persistence: {
      n: number
      mae: number | null
      gameweeks: number[]
      unavailable_reason?: string
    }
  }
  limitations?: string[]
}

export interface SeasonCalibration {
  schema_version: number
  calibration_version: string
  season: string | null
  entry_id: number | null
  generated_at: string
  status: 'measured' | 'insufficient_data' | 'unavailable'
  headline: string
  measures?: string
  distribution: DistributionCalibration
  projection: ProjectionCalibration
  awaiting_result?: number[]
  sources?: Record<string, unknown>
  limitations: string[]
}

export type CalibrationState =
  | { kind: 'missing' }
  | { kind: 'malformed'; detail: string }
  | { kind: 'unsupported'; version: unknown; detail: string }
  | { kind: 'ok'; data: SeasonCalibration }

/** The calibration block carried by a review artifact, or null. */
export function seasonCalibrationBlock(review: unknown): unknown {
  if (review == null || typeof review !== 'object' || Array.isArray(review)) return null
  return (review as Record<string, unknown>).season_calibration ?? null
}

/**
 * Validate an in-season calibration block.
 *
 * Strict for the same reason `parseBacktest` is, and for one more: a block that
 * lost its `n` fields still renders a mean, and a mean without its count is the
 * exact failure this feature was built to stop. So `distribution` and its two
 * populations are required, and each population must carry a numeric `n`.
 */
export function parseSeasonCalibration(raw: unknown): CalibrationState {
  if (raw == null) return { kind: 'missing' }
  if (typeof raw !== 'object' || Array.isArray(raw)) {
    return {
      kind: 'malformed',
      detail: `expected an object, got ${Array.isArray(raw) ? 'an array' : typeof raw}`,
    }
  }
  const obj = raw as Record<string, unknown>
  const version = obj.schema_version
  if (typeof version !== 'number'
      || !(SUPPORTED_CALIBRATION_VERSIONS as readonly number[]).includes(version)) {
    return {
      kind: 'unsupported',
      version,
      detail: `calibration schema_version ${JSON.stringify(version)} is not renderable ` +
        `by this build (supported: ${SUPPORTED_CALIBRATION_VERSIONS.join(', ')}).`,
    }
  }
  const dist = obj.distribution as Record<string, unknown> | undefined
  if (!dist || typeof dist !== 'object') {
    return { kind: 'malformed', detail: "'distribution' must be an object" }
  }
  for (const pop of ['followed_the_advice', 'every_gameweek'] as const) {
    const stats = dist[pop] as Record<string, unknown> | undefined
    if (!stats || typeof stats.n !== 'number') {
      return {
        kind: 'malformed',
        detail: `'distribution.${pop}.n' must be a number — a calibration figure ` +
          'may not be rendered without the sample behind it',
      }
    }
  }
  if (typeof dist.reportable !== 'boolean') {
    return { kind: 'malformed', detail: "'distribution.reportable' must be a boolean" }
  }
  if (typeof obj.headline !== 'string') {
    return { kind: 'malformed', detail: "'headline' must be a string" }
  }
  if (!Array.isArray(obj.limitations)) {
    return { kind: 'malformed', detail: "'limitations' must be an array" }
  }
  return { kind: 'ok', data: obj as unknown as SeasonCalibration }
}

/** Read a calibration block straight off a review artifact. */
export function parseReviewCalibration(review: unknown): CalibrationState {
  return parseSeasonCalibration(seasonCalibrationBlock(review))
}

/**
 * "n = 3 gameweeks", ready to sit beside a figure.
 *
 * A function rather than a template literal at each call site, because there are
 * a dozen call sites and every one of them has to be right.
 */
export function sampleLabel(n: number, unit = 'gameweek'): string {
  return `n = ${n.toLocaleString()} ${unit}${n === 1 ? '' : 's'}`
}

export const PIT_DIRECTION_LABELS: Record<PitDirection, string> = {
  runs_hot: 'Simulation runs hot — results land low in it',
  runs_cold: 'Simulation runs cold — results land high in it',
  no_detectable_bias: 'No detectable bias',
}

/**
 * The gameweeks that can be plotted: a percentile, and the advice followed.
 *
 * The divergent ones are deliberately not filtered out of the artifact — they
 * are shown in the table, labelled — but they must not be drawn as though they
 * measured the same thing.
 */
export function pitPoints(d: DistributionCalibration): PitGameweek[] {
  return (d.per_gameweek ?? []).filter((g) => typeof g.percentile === 'number')
}

/**
 * True when a figure in this block may be quoted as a finding.
 *
 * One place, so "is this reportable?" cannot be answered differently in two
 * parts of the page.
 */
export function calibrationReportable(c: SeasonCalibration): boolean {
  return c.distribution.reportable === true || c.projection.reportable === true
}
