"""1.14 -- `data/backtest.json` is generated by hand and by nothing else.

`python -m gaffer.backtest --write` appears in neither `pipeline.py` nor any
workflow, so the Accuracy page serves whatever was last committed. A fix to
`backtest.py` never reaches the site on its own: U13's fix went green in the
source while the live page still read UNDEFINED after a deploy, and
regenerating on 2026-08-16 also shipped a limitation written the previous day
that had been sitting unpublished.

Running the full backtest on every refresh is the wrong answer -- it scores
161,700 predictions and the refresh is asked for every 15 minutes. Detecting
the drift is the right one.

ADVISORY: this cannot be fixed by the pipeline, only by a person running the
regeneration, so it must not block publishing. It reports, loudly.
"""
from __future__ import annotations

import subprocess

import pytest

from gaffer import config

SOURCE = "src/gaffer/backtest.py"
ARTIFACT = "data/backtest.json"


def _last_commit_epoch(path: str) -> int | None:
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%ct", "--", path],
            cwd=config.REPO_ROOT, capture_output=True, text=True, timeout=20,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if out.returncode != 0 or not out.stdout.strip():
        return None
    try:
        return int(out.stdout.strip())
    except ValueError:
        return None


@pytest.mark.advisory
def test_the_published_backtest_is_not_older_than_the_code_that_produces_it():
    src = _last_commit_epoch(SOURCE)
    art = _last_commit_epoch(ARTIFACT)
    if src is None or art is None:
        pytest.skip("no git history available to compare")
    assert art >= src, (
        f"{ARTIFACT} was last committed {src - art}s before the most recent "
        f"change to {SOURCE}, so the Accuracy page is serving numbers that "
        "predate the model they claim to describe. Regenerate with "
        "`python -m gaffer.backtest --write` and commit the result."
    )


def test_the_schema_the_reader_expects_is_the_schema_published():
    """Blocking, unlike the staleness check: a schema mismatch is not a stale
    number, it is a page that cannot render its own evidence."""
    import json

    from gaffer import backtest as BT

    path = config.REPO_ROOT / ARTIFACT
    if not path.exists():
        pytest.skip("no backtest artifact")
    blob = json.loads(path.read_text(encoding="utf-8"))
    assert blob.get("schema_version") == BT.SCHEMA_VERSION, (
        "backtest.json schema does not match the reader; the Accuracy page "
        "will refuse it")
